#include <fstream>
#include <iostream>
#include <string>

int main()
{
    const std::string filename = "hello.txt";

    std::ofstream file(filename);

    if (!file.is_open())
    {
        std::cerr << "Failed to create " << filename << std::endl;
        return 1;
    }

    file << "Hello! The file is generated by C++ running on GitHub Actions.\n";
    file << "this is the first push.\n";

    file.close();

    std::cout << "File generated successfully: " << filename << std::endl;

    return 0;
}
